# syntax=docker/dockerfile:1
ARG PYTHON_VERSION={{ python_version }}
FROM python:$PYTHON_VERSION-slim AS base

LABEL org.opencontainers.image.description "{{ description }}"

# Configure Python to print tracebacks on crash [1], and to not buffer stdout and stderr [2].
# [1] https://docs.python.org/3/using/cmdline.html#envvar-PYTHONFAULTHANDLER
# [2] https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUNBUFFERED
ENV PYTHONFAULTHANDLER 1
ENV PYTHONUNBUFFERED 1

# Install Poetry.
ENV POETRY_VERSION 1.7.1
RUN --mount=type=cache,target=/root/.cache/pip/ \
    pip install poetry==$POETRY_VERSION

# Install curl & compilers that may be required for certain packages or platforms.
# The stock ubuntu image cleans up /var/cache/apt automatically. This makes the build process slow.
# Enable apt caching by removing docker-clean
RUN rm /etc/apt/apt.conf.d/docker-clean
RUN --mount=type=cache,target=/var/cache/apt/ \
    --mount=type=cache,target=/var/lib/apt/ \
    apt-get update && \
    apt-get install --no-install-recommends --yes curl build-essential git zsh

# Create and activate a virtual environment.
RUN python -m venv /opt/{{ package_slug }}-env
ENV PATH /opt/{{ package_slug }}-env/bin:$PATH
ENV VIRTUAL_ENV /opt/{{ package_slug }}-env

# Set the working directory.
WORKDIR /workspaces/{{ package_slug }}/

# Install the run time Python dependencies in the virtual environment.
COPY poetry.lock* pyproject.toml /workspaces/{{ package_slug }}/
RUN mkdir -p /root/.cache/pypoetry/ && mkdir -p /root/.config/pypoetry/ && \
    mkdir -p src/{{ package_slug }}/ && touch src/{{ package_slug }}/__init__.py && touch README.md
RUN --mount=type=cache,target=/root/.cache/pypoetry/ \{% if use_private_package_repository %}
    --mount=type=secret,id=poetry-auth,target=/root/.config/pypoetry/auth.toml,ro \{% endif %}
    poetry install --only main --no-interaction --no-ansi



FROM base AS dev

# Install docker & starship prompt.
RUN --mount=type=cache,target=/var/cache/apt/ \
    --mount=type=cache,target=/var/lib/apt/ \
    curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh && \
    sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- "--yes" && \
    echo 'eval "$(starship init zsh)"' >> ~/.zshrc && \
    echo 'poe --help' >> ~/.zshrc && \
    zsh -c 'source ~/.zshrc'

# Install the development Python dependencies in the virtual environment.
RUN --mount=type=cache,target=/root/.cache/pypoetry/ \{% if use_private_package_repository %}
    --mount=type=secret,id=poetry-auth,target=/root/.config/pypoetry/auth.toml,ro \{% endif %}
    poetry install --no-interaction --no-ansi

# Install pre-commit hooks.
COPY .pre-commit-config.yaml /workspaces/{{ package_slug }}/
RUN git init && git config --global --add safe.directory /workspaces/{{ package_slug }} && \
    pre-commit install --install-hooks

{% if use_private_package_repository %}# Enable Poetry to read the private package repository credentials.
RUN ln -s /run/secrets/poetry-auth /root/.config/pypoetry/auth.toml

{% endif %}CMD ["zsh"]



{% if use_app %}FROM base AS app

# Copy the package source code.
COPY . .

ENTRYPOINT ["/opt/{{ package_slug }}-env/bin/poe"]
CMD ["serve"]

# Provide build information as environment variables.
ARG BUILD_BRANCH
ENV BUILD_BRANCH $BUILD_BRANCH
ARG BUILD_COMMIT
ENV BUILD_COMMIT $BUILD_COMMIT
ARG BUILD_TIMESTAMP
ENV BUILD_TIMESTAMP $BUILD_TIMESTAMP
{% endif %}