name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]
    name: PyTest (Python ${{ matrix.python-version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Uv
        working-directory: testing
        run: |
          pip install uv==0.12.6
          uv sync

      - name: Run Python Tests
        working-directory: testing
        run: uv run -m pytest

  generate_package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]
    name: Generate Package (Python ${{ matrix.python-version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "**/uv.lock"

      - name: Generate Python package
        run: |
          rm -Rf .git/
          uvx copier copy . ./generated/ \
            --quiet \
            --data ci="github" \
            --data repository_url="https://github.com/lukin0110/mcfly/" \
            --data name="McFly" \
            --data description="A package used in tests to test a scaffolded python package" \
            --data package_type="package" \
            --data use_pydantic=yes \
            --data use_makefile=no \
            --data python_version="${{ matrix.python-version }}" \
            --data package_slug="mcfly"

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install @devcontainers/cli
        run: npm install --location=global @devcontainers/cli@0.54.2

      - name: Start Dev Container
        working-directory: generated
        env:
          DOCKER_BUILDKIT: 1
        run: |
          git init
          git add .
          uv lock
          devcontainer up --workspace-folder .

      - name: Lint package
        working-directory: generated
        run: devcontainer exec --workspace-folder . poe lint

      - name: Test package
        working-directory: generated
        run: devcontainer exec --workspace-folder . poe test

  generate_fastapi:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]
    name: Generate FastAPI app (Python ${{ matrix.python-version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "**/uv.lock"

      - name: Generate FastAPI app
        run: |
          rm -Rf .git/
          uvx copier copy . ./generated/ \
            --quiet \
            --data ci="github" \
            --data repository_url="https://github.com/lukin0110/mcfly-api/" \
            --data name="McFly API" \
            --data description="A package used in tests to test a scaffolded FastAPI app" \
            --data package_type="fastapi" \
            --data use_pydantic=yes \
            --data use_makefile=no \
            --data python_version="${{ matrix.python-version }}" \
            --data package_slug="mcfly"

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install @devcontainers/cli
        run: npm install --location=global @devcontainers/cli@0.54.2

      - name: Start Dev Container
        working-directory: generated
        env:
          DOCKER_BUILDKIT: 1
        run: |
          git init
          git add .
          uv lock
          devcontainer up --workspace-folder .

      - name: Lint package
        working-directory: generated
        run: devcontainer exec --workspace-folder . poe lint

      - name: Test package
        working-directory: generated
        run: devcontainer exec --workspace-folder . poe test
